-- LISTA DI CASA — Supabase schema
-- À exécuter une seule fois dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 60),
  created_at timestamptz not null default now()
);

create table if not exists public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Notre maison',
  join_code text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.household_members (
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (household_id, user_id)
);

create table if not exists public.shopping_items (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  quantity text check (quantity is null or char_length(quantity) <= 20),
  is_done boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.house_tasks (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  is_urgent boolean not null default false,
  assignee uuid references auth.users(id) on delete set null,
  is_done boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- Petit journal technique utilisé uniquement pour réveiller l'autre téléphone
-- après une modification. Cela rend aussi les suppressions fiables en temps réel.
create table if not exists public.sync_events (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_household_members_user on public.household_members(user_id);
create index if not exists idx_shopping_household on public.shopping_items(household_id);
create index if not exists idx_tasks_household on public.house_tasks(household_id);

-- Crée automatiquement le profil après inscription.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helpers sécurisés pour les politiques RLS.
create or replace function public.is_household_member(hid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members hm
    where hm.household_id = hid
      and hm.user_id = auth.uid()
  );
$$;

create or replace function public.shares_household(target_uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members me
    join public.household_members them
      on them.household_id = me.household_id
    where me.user_id = auth.uid()
      and them.user_id = target_uid
  );
$$;

-- Créer une maison + ajouter automatiquement son créateur.
create or replace function public.create_household(household_name text default 'Notre maison')
returns table (id uuid, name text, join_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  new_code text;
  clean_name text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if exists (select 1 from public.household_members where user_id = auth.uid()) then
    raise exception 'User already belongs to a household';
  end if;

  clean_name := coalesce(nullif(trim(household_name), ''), 'Notre maison');

  loop
    new_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (select 1 from public.households h where h.join_code = new_code);
  end loop;

  insert into public.households (name, join_code, created_by)
  values (clean_name, new_code, auth.uid())
  returning households.id into new_id;

  insert into public.household_members (household_id, user_id)
  values (new_id, auth.uid());

  return query
  select h.id, h.name, h.join_code
  from public.households h
  where h.id = new_id;
end;
$$;

-- Rejoindre une maison uniquement avec son code.
create or replace function public.join_household(household_code text)
returns table (id uuid, name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if exists (select 1 from public.household_members where user_id = auth.uid()) then
    raise exception 'User already belongs to a household';
  end if;

  select h.id into target_id
  from public.households h
  where h.join_code = upper(trim(household_code))
  limit 1;

  if target_id is null then
    raise exception 'Invalid household code';
  end if;

  insert into public.household_members (household_id, user_id)
  values (target_id, auth.uid())
  on conflict do nothing;

  return query
  select h.id, h.name from public.households h where h.id = target_id;
end;
$$;

revoke all on function public.create_household(text) from public;
revoke all on function public.join_household(text) from public;
revoke all on function public.is_household_member(uuid) from public;
revoke all on function public.shares_household(uuid) from public;

grant execute on function public.create_household(text) to authenticated;
grant execute on function public.join_household(text) to authenticated;
grant execute on function public.is_household_member(uuid) to authenticated;
grant execute on function public.shares_household(uuid) to authenticated;

-- RLS
alter table public.profiles enable row level security;
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.shopping_items enable row level security;
alter table public.house_tasks enable row level security;
alter table public.sync_events enable row level security;

drop policy if exists "profiles_select_housemates" on public.profiles;
create policy "profiles_select_housemates"
on public.profiles for select to authenticated
using (id = auth.uid() or public.shares_household(id));

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "households_select_member" on public.households;
create policy "households_select_member"
on public.households for select to authenticated
using (public.is_household_member(id));

drop policy if exists "members_select_same_household" on public.household_members;
create policy "members_select_same_household"
on public.household_members for select to authenticated
using (user_id = auth.uid() or public.is_household_member(household_id));

drop policy if exists "shopping_select_member" on public.shopping_items;
create policy "shopping_select_member"
on public.shopping_items for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "shopping_insert_member" on public.shopping_items;
create policy "shopping_insert_member"
on public.shopping_items for insert to authenticated
with check (public.is_household_member(household_id) and created_by = auth.uid());

drop policy if exists "shopping_update_member" on public.shopping_items;
create policy "shopping_update_member"
on public.shopping_items for update to authenticated
using (public.is_household_member(household_id))
with check (public.is_household_member(household_id));

drop policy if exists "shopping_delete_member" on public.shopping_items;
create policy "shopping_delete_member"
on public.shopping_items for delete to authenticated
using (public.is_household_member(household_id));

drop policy if exists "tasks_select_member" on public.house_tasks;
create policy "tasks_select_member"
on public.house_tasks for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "tasks_insert_member" on public.house_tasks;
create policy "tasks_insert_member"
on public.house_tasks for insert to authenticated
with check (public.is_household_member(household_id) and created_by = auth.uid());

drop policy if exists "tasks_update_member" on public.house_tasks;
create policy "tasks_update_member"
on public.house_tasks for update to authenticated
using (public.is_household_member(household_id))
with check (
  public.is_household_member(household_id)
  and (assignee is null or public.shares_household(assignee))
  and (completed_by is null or public.shares_household(completed_by))
);

drop policy if exists "tasks_delete_member" on public.house_tasks;
create policy "tasks_delete_member"
on public.house_tasks for delete to authenticated
using (public.is_household_member(household_id));

grant select, update on public.profiles to authenticated;
grant select on public.households to authenticated;
grant select on public.household_members to authenticated;
grant select, insert, update, delete on public.shopping_items to authenticated;
grant select, insert, update, delete on public.house_tasks to authenticated;

-- Les clients peuvent lire uniquement les événements de leur propre maison.
drop policy if exists "sync_events_select_member" on public.sync_events;
create policy "sync_events_select_member"
on public.sync_events for select to authenticated
using (public.is_household_member(household_id));

grant select on public.sync_events to authenticated;

-- À chaque changement de liste, on écrit un événement minimal contenant
-- uniquement l'identifiant de la maison. Le contenu des listes reste dans
-- les tables protégées par RLS.
create or replace function public.emit_household_sync_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  hid uuid;
begin
  if tg_op = 'DELETE' then
    hid := old.household_id;
  else
    hid := new.household_id;
  end if;

  insert into public.sync_events (household_id) values (hid);
  return coalesce(new, old);
end;
$$;

drop trigger if exists shopping_emit_sync on public.shopping_items;
create trigger shopping_emit_sync
after insert or update or delete on public.shopping_items
for each row execute procedure public.emit_household_sync_event();

drop trigger if exists tasks_emit_sync on public.house_tasks;
create trigger tasks_emit_sync
after insert or update or delete on public.house_tasks
for each row execute procedure public.emit_household_sync_event();

-- Active Realtime sur le journal de synchronisation et les membres.

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sync_events'
  ) then
    alter publication supabase_realtime add table public.sync_events;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'household_members'
  ) then
    alter publication supabase_realtime add table public.household_members;
  end if;
end $$;
