-- LISTA DI CASA — Supabase schema
-- À exécuter une seule fois dans Supabase > SQL Editor.

create extension if not exists pgcrypto;
create extension if not exists unaccent;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 60),
  profile_icon text not null default 'initial' check (char_length(profile_icon) between 1 and 24),
  profile_color text not null default '#8A5CFF' check (profile_color ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Notre maison',
  join_code text not null unique,
  shared_quote text not null default 'Les petites choses font les grands foyers.' check (char_length(shared_quote) between 1 and 100),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.household_members (
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (household_id, user_id)
);

create table if not exists public.shopping_items (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  quantity text check (quantity is null or char_length(quantity) <= 20),
  category text not null default 'other',
  is_done boolean not null default false,
  is_urgent boolean not null default false,
  saved_for_later boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.house_tasks (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  is_urgent boolean not null default false,
  assignee uuid references auth.users(id) on delete set null,
  is_done boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shopping_history (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  normalized_name text not null,
  display_name text not null check (char_length(display_name) between 1 and 100),
  last_quantity text check (last_quantity is null or char_length(last_quantity) <= 20),
  last_urgent boolean not null default false,
  last_category text not null default 'other',
  use_count integer not null default 1 check (use_count >= 1),
  last_used_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (household_id, normalized_name)
);


-- Petit journal technique utilisé uniquement pour réveiller l'autre téléphone
-- après une modification. Cela rend aussi les suppressions fiables en temps réel.
create table if not exists public.sync_events (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_household_members_user on public.household_members(user_id);
create index if not exists idx_shopping_household on public.shopping_items(household_id);
create index if not exists idx_shopping_history_household on public.shopping_history(household_id, last_used_at desc);
create index if not exists idx_tasks_household on public.house_tasks(household_id);

-- Crée automatiquement le profil après inscription.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helpers sécurisés pour les politiques RLS.
create or replace function public.is_household_member(hid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members hm
    where hm.household_id = hid
      and hm.user_id = auth.uid()
  );
$$;

create or replace function public.shares_household(target_uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members me
    join public.household_members them
      on them.household_id = me.household_id
    where me.user_id = auth.uid()
      and them.user_id = target_uid
  );
$$;

-- Créer une maison + ajouter automatiquement son créateur.
create or replace function public.create_household(household_name text default 'Notre maison')
returns table (id uuid, name text, join_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  new_code text;
  clean_name text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if exists (select 1 from public.household_members where user_id = auth.uid()) then
    raise exception 'User already belongs to a household';
  end if;

  clean_name := coalesce(nullif(trim(household_name), ''), 'Notre maison');

  loop
    new_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (select 1 from public.households h where h.join_code = new_code);
  end loop;

  insert into public.households (name, join_code, created_by)
  values (clean_name, new_code, auth.uid())
  returning households.id into new_id;

  insert into public.household_members (household_id, user_id)
  values (new_id, auth.uid());

  return query
  select h.id, h.name, h.join_code
  from public.households h
  where h.id = new_id;
end;
$$;

-- Rejoindre une maison uniquement avec son code.
create or replace function public.join_household(household_code text)
returns table (id uuid, name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if exists (select 1 from public.household_members where user_id = auth.uid()) then
    raise exception 'User already belongs to a household';
  end if;

  select h.id into target_id
  from public.households h
  where h.join_code = upper(trim(household_code))
  limit 1;

  if target_id is null then
    raise exception 'Invalid household code';
  end if;

  insert into public.household_members (household_id, user_id)
  values (target_id, auth.uid())
  on conflict do nothing;

  return query
  select h.id, h.name from public.households h where h.id = target_id;
end;
$$;

revoke all on function public.create_household(text) from public;
revoke all on function public.join_household(text) from public;
revoke all on function public.is_household_member(uuid) from public;
revoke all on function public.shares_household(uuid) from public;

grant execute on function public.create_household(text) to authenticated;
grant execute on function public.join_household(text) to authenticated;
grant execute on function public.is_household_member(uuid) to authenticated;
grant execute on function public.shares_household(uuid) to authenticated;

-- RLS
alter table public.profiles enable row level security;
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.shopping_items enable row level security;
alter table public.shopping_history enable row level security;
alter table public.house_tasks enable row level security;
alter table public.sync_events enable row level security;

drop policy if exists "profiles_select_housemates" on public.profiles;
create policy "profiles_select_housemates"
on public.profiles for select to authenticated
using (id = auth.uid() or public.shares_household(id));

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "households_select_member" on public.households;
create policy "households_select_member"
on public.households for select to authenticated
using (public.is_household_member(id));

drop policy if exists "households_update_member" on public.households;
create policy "households_update_member"
on public.households for update to authenticated
using (public.is_household_member(id))
with check (public.is_household_member(id));

drop policy if exists "members_select_same_household" on public.household_members;
create policy "members_select_same_household"
on public.household_members for select to authenticated
using (user_id = auth.uid() or public.is_household_member(household_id));

drop policy if exists "shopping_select_member" on public.shopping_items;
create policy "shopping_select_member"
on public.shopping_items for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "shopping_insert_member" on public.shopping_items;
create policy "shopping_insert_member"
on public.shopping_items for insert to authenticated
with check (public.is_household_member(household_id) and created_by = auth.uid());

drop policy if exists "shopping_update_member" on public.shopping_items;
create policy "shopping_update_member"
on public.shopping_items for update to authenticated
using (public.is_household_member(household_id))
with check (public.is_household_member(household_id));

drop policy if exists "shopping_delete_member" on public.shopping_items;
create policy "shopping_delete_member"
on public.shopping_items for delete to authenticated
using (public.is_household_member(household_id));

drop policy if exists "shopping_history_select_member" on public.shopping_history;
create policy "shopping_history_select_member"
on public.shopping_history for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "shopping_history_insert_member" on public.shopping_history;
create policy "shopping_history_insert_member"
on public.shopping_history for insert to authenticated
with check (public.is_household_member(household_id));

drop policy if exists "shopping_history_update_member" on public.shopping_history;
create policy "shopping_history_update_member"
on public.shopping_history for update to authenticated
using (public.is_household_member(household_id))
with check (public.is_household_member(household_id));

drop policy if exists "shopping_history_delete_member" on public.shopping_history;
create policy "shopping_history_delete_member"
on public.shopping_history for delete to authenticated
using (public.is_household_member(household_id));

drop policy if exists "tasks_select_member" on public.house_tasks;
create policy "tasks_select_member"
on public.house_tasks for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "tasks_insert_member" on public.house_tasks;
create policy "tasks_insert_member"
on public.house_tasks for insert to authenticated
with check (public.is_household_member(household_id) and created_by = auth.uid());

drop policy if exists "tasks_update_member" on public.house_tasks;
create policy "tasks_update_member"
on public.house_tasks for update to authenticated
using (public.is_household_member(household_id))
with check (
  public.is_household_member(household_id)
  and (assignee is null or public.shares_household(assignee))
  and (completed_by is null or public.shares_household(completed_by))
);

drop policy if exists "tasks_delete_member" on public.house_tasks;
create policy "tasks_delete_member"
on public.house_tasks for delete to authenticated
using (public.is_household_member(household_id));

grant select, update on public.profiles to authenticated;
grant select on public.households to authenticated;
grant update (shared_quote) on public.households to authenticated;
grant select on public.household_members to authenticated;
grant select, insert, update, delete on public.shopping_items to authenticated;
grant select, insert, update, delete on public.shopping_history to authenticated;
grant select, insert, update, delete on public.house_tasks to authenticated;

-- Les clients peuvent lire uniquement les événements de leur propre maison.
drop policy if exists "sync_events_select_member" on public.sync_events;
create policy "sync_events_select_member"
on public.sync_events for select to authenticated
using (public.is_household_member(household_id));

grant select on public.sync_events to authenticated;

-- À chaque changement de liste, on écrit un événement minimal contenant
-- uniquement l'identifiant de la maison. Le contenu des listes reste dans
-- les tables protégées par RLS.
create or replace function public.emit_household_sync_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  hid uuid;
begin
  if tg_op = 'DELETE' then
    hid := old.household_id;
  else
    hid := new.household_id;
  end if;

  insert into public.sync_events (household_id) values (hid);
  return coalesce(new, old);
end;
$$;

drop trigger if exists shopping_emit_sync on public.shopping_items;
create trigger shopping_emit_sync
after insert or update or delete on public.shopping_items
for each row execute procedure public.emit_household_sync_event();

drop trigger if exists shopping_history_emit_sync on public.shopping_history;
create trigger shopping_history_emit_sync
after insert or update or delete on public.shopping_history
for each row execute procedure public.emit_household_sync_event();

drop trigger if exists tasks_emit_sync on public.house_tasks;
create trigger tasks_emit_sync
after insert or update or delete on public.house_tasks
for each row execute procedure public.emit_household_sync_event();

-- Active Realtime sur le journal de synchronisation et les membres.

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sync_events'
  ) then
    alter publication supabase_realtime add table public.sync_events;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'household_members'
  ) then
    alter publication supabase_realtime add table public.household_members;
  end if;
end $$;


-- LISTA DI CASA — MIGRATION V5 : CATÉGORIES REPLIABLES + PERSONNALISÉES
-- À exécuter UNE FOIS dans Supabase > SQL Editor avant de publier la V5.
-- Cette migration conserve les courses, l'historique et les catégories V4 existantes.

-- 1) Table partagée des catégories de courses.
create table if not exists public.shopping_categories (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  category_key text not null default ('custom_' || replace(gen_random_uuid()::text, '-', '')),
  name_fr text not null check (char_length(name_fr) between 1 and 40),
  name_en text not null check (char_length(name_en) between 1 and 40),
  emoji text not null default '📦' check (char_length(emoji) between 1 and 16),
  sort_order integer not null default 100,
  is_default boolean not null default false,
  is_fallback boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (household_id, category_key)
);

create index if not exists idx_shopping_categories_household
  on public.shopping_categories(household_id, sort_order);

-- 2) Ajoute les 9 catégories de base à toutes les maisons déjà existantes.
insert into public.shopping_categories
  (household_id, category_key, name_fr, name_en, emoji, sort_order, is_default, is_fallback)
select
  h.id,
  v.category_key,
  v.name_fr,
  v.name_en,
  v.emoji,
  v.sort_order,
  true,
  v.is_fallback
from public.households h
cross join (values
  ('fruit_veg', 'Fruits & légumes', 'Fruit & Veg', '🥬', 10, false),
  ('bakery', 'Boulangerie', 'Bakery', '🥖', 20, false),
  ('fresh', 'Produits frais', 'Chilled & Dairy', '🥛', 30, false),
  ('meat_fish', 'Viande & poisson', 'Meat & Fish', '🥩', 40, false),
  ('pantry', 'Épicerie', 'Pantry', '🥫', 50, false),
  ('drinks', 'Boissons', 'Drinks', '🥤', 60, false),
  ('frozen', 'Surgelés', 'Frozen', '❄️', 70, false),
  ('home', 'Maison', 'Household', '🧽', 80, false),
  ('other', 'Autres', 'Other', '📦', 90, true)
) as v(category_key, name_fr, name_en, emoji, sort_order, is_fallback)
on conflict (household_id, category_key) do nothing;

-- 3) Sécurité : seules les personnes de la même maison voient/modifient les catégories.
alter table public.shopping_categories enable row level security;

drop policy if exists "shopping_categories_select_member" on public.shopping_categories;
create policy "shopping_categories_select_member"
on public.shopping_categories for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "shopping_categories_insert_member" on public.shopping_categories;
create policy "shopping_categories_insert_member"
on public.shopping_categories for insert to authenticated
with check (
  public.is_household_member(household_id)
  and (created_by is null or created_by = auth.uid())
);

drop policy if exists "shopping_categories_update_member" on public.shopping_categories;
create policy "shopping_categories_update_member"
on public.shopping_categories for update to authenticated
using (public.is_household_member(household_id))
with check (public.is_household_member(household_id));

drop policy if exists "shopping_categories_delete_member" on public.shopping_categories;
create policy "shopping_categories_delete_member"
on public.shopping_categories for delete to authenticated
using (public.is_household_member(household_id));

grant select, insert, update, delete on public.shopping_categories to authenticated;

-- 4) Une modification de catégorie réveille aussi l'autre téléphone.
drop trigger if exists shopping_categories_emit_sync on public.shopping_categories;
create trigger shopping_categories_emit_sync
after insert or update or delete on public.shopping_categories
for each row execute procedure public.emit_household_sync_event();

-- 5) Suppression sécurisée : les articles/historiques de la catégorie sont déplacés
-- vers "Autres" avant la suppression. "Autres" elle-même est protégée.
create or replace function public.delete_shopping_category(category_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  cat public.shopping_categories%rowtype;
  fallback_key text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select * into cat
  from public.shopping_categories
  where id = category_id;

  if not found then
    raise exception 'Category not found';
  end if;

  if not public.is_household_member(cat.household_id) then
    raise exception 'Not allowed';
  end if;

  if cat.is_fallback then
    raise exception 'Fallback category cannot be deleted';
  end if;

  select c.category_key into fallback_key
  from public.shopping_categories c
  where c.household_id = cat.household_id
    and c.is_fallback = true
  order by c.sort_order
  limit 1;

  fallback_key := coalesce(fallback_key, 'other');

  update public.shopping_items
  set category = fallback_key,
      updated_at = now()
  where household_id = cat.household_id
    and category = cat.category_key;

  update public.shopping_history
  set last_category = fallback_key
  where household_id = cat.household_id
    and last_category = cat.category_key;

  delete from public.shopping_categories
  where id = cat.id;
end;
$$;

revoke all on function public.delete_shopping_category(uuid) from public;
grant execute on function public.delete_shopping_category(uuid) to authenticated;

-- 6) Les nouvelles maisons reçoivent automatiquement les catégories de base.
create or replace function public.create_household(household_name text default 'Notre maison')
returns table (id uuid, name text, join_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  new_code text;
  clean_name text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if exists (select 1 from public.household_members where user_id = auth.uid()) then
    raise exception 'User already belongs to a household';
  end if;

  clean_name := coalesce(nullif(trim(household_name), ''), 'Notre maison');

  loop
    new_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (select 1 from public.households h where h.join_code = new_code);
  end loop;

  insert into public.households (name, join_code, created_by)
  values (clean_name, new_code, auth.uid())
  returning households.id into new_id;

  insert into public.household_members (household_id, user_id)
  values (new_id, auth.uid());

  insert into public.shopping_categories
    (household_id, category_key, name_fr, name_en, emoji, sort_order, is_default, is_fallback)
  values
    (new_id, 'fruit_veg', 'Fruits & légumes', 'Fruit & Veg', '🥬', 10, true, false),
    (new_id, 'bakery', 'Boulangerie', 'Bakery', '🥖', 20, true, false),
    (new_id, 'fresh', 'Produits frais', 'Chilled & Dairy', '🥛', 30, true, false),
    (new_id, 'meat_fish', 'Viande & poisson', 'Meat & Fish', '🥩', 40, true, false),
    (new_id, 'pantry', 'Épicerie', 'Pantry', '🥫', 50, true, false),
    (new_id, 'drinks', 'Boissons', 'Drinks', '🥤', 60, true, false),
    (new_id, 'frozen', 'Surgelés', 'Frozen', '❄️', 70, true, false),
    (new_id, 'home', 'Maison', 'Household', '🧽', 80, true, false),
    (new_id, 'other', 'Autres', 'Other', '📦', 90, true, true)
  on conflict (household_id, category_key) do nothing;

  return query
  select h.id, h.name, h.join_code
  from public.households h
  where h.id = new_id;
end;
$$;

grant execute on function public.create_household(text) to authenticated;



-- LISTA DI CASA — MIGRATION V6 : ACHATS MAISON
-- À exécuter UNE FOIS dans Supabase > SQL Editor avant de publier la V6.
-- Cette migration conserve toutes les données existantes.

-- 1) Liste séparée des achats ponctuels pour la maison.
create table if not exists public.home_purchases (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  assignee uuid references auth.users(id) on delete set null,
  is_urgent boolean not null default false,
  estimated_price numeric(10,2) check (estimated_price is null or estimated_price >= 0),
  note text check (note is null or char_length(note) <= 500),
  url text check (url is null or char_length(url) <= 1000),
  status text not null default 'todo' check (status in ('todo', 'later', 'bought')),
  created_by uuid not null references auth.users(id) on delete cascade,
  bought_by uuid references auth.users(id) on delete set null,
  bought_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_home_purchases_household
  on public.home_purchases(household_id, status, created_at desc);

-- 2) Sécurité : seuls les membres de la maison peuvent voir et modifier ces achats.
alter table public.home_purchases enable row level security;

drop policy if exists "home_purchases_select_member" on public.home_purchases;
create policy "home_purchases_select_member"
on public.home_purchases for select to authenticated
using (public.is_household_member(household_id));

drop policy if exists "home_purchases_insert_member" on public.home_purchases;
create policy "home_purchases_insert_member"
on public.home_purchases for insert to authenticated
with check (
  public.is_household_member(household_id)
  and created_by = auth.uid()
  and (assignee is null or public.shares_household(assignee))
  and (bought_by is null or public.shares_household(bought_by))
);

drop policy if exists "home_purchases_update_member" on public.home_purchases;
create policy "home_purchases_update_member"
on public.home_purchases for update to authenticated
using (public.is_household_member(household_id))
with check (
  public.is_household_member(household_id)
  and (assignee is null or public.shares_household(assignee))
  and (bought_by is null or public.shares_household(bought_by))
);

drop policy if exists "home_purchases_delete_member" on public.home_purchases;
create policy "home_purchases_delete_member"
on public.home_purchases for delete to authenticated
using (public.is_household_member(household_id));

grant select, insert, update, delete on public.home_purchases to authenticated;

-- 3) Chaque modification réveille l'autre téléphone via le journal de synchro existant.
drop trigger if exists home_purchases_emit_sync on public.home_purchases;
create trigger home_purchases_emit_sync
after insert or update or delete on public.home_purchases
for each row execute procedure public.emit_household_sync_event();



-- CASAMI V9 — synchronisation profil + phrase commune
create or replace function public.emit_household_self_sync_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.sync_events (household_id) values (new.id);
  return new;
end;
$$;

drop trigger if exists households_emit_sync on public.households;
create trigger households_emit_sync
after update on public.households
for each row execute procedure public.emit_household_self_sync_event();

create or replace function public.emit_profile_sync_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.sync_events (household_id)
  select hm.household_id from public.household_members hm where hm.user_id = new.id;
  return new;
end;
$$;

drop trigger if exists profiles_emit_sync on public.profiles;
create trigger profiles_emit_sync
after update of profile_icon, profile_color, display_name on public.profiles
for each row execute procedure public.emit_profile_sync_events();
